[package]
name = "abc335"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.12.0"
proconio = { version = "0.4.3", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
